# Generated by Django 4.2.14 on 2024-10-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='cus_image',
            field=models.ImageField(default='null', upload_to='static/customers/'),
        ),
    ]
